DROP TABLE MENU_ITEMS;
DROP TABLE ORDERS;

CREATE TABLE MENU_ITEM_TYPES (
  MENU_ITEM_TYPE_ID NUMBER(10, 0) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR2(255) NOT NULL,
  PRIMARY KEY (MENU_ITEM_TYPE_ID));

CREATE TABLE MENU_ITEMS (
  MENU_ITEM_ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
  MENU_ITEM_TYPE_ID NUMBER(10, 0) NOT NULL,
  NAME VARCHAR2(255) NOT NULL,
  PRICE NUMBER(4, 2) NOT NULL,
  PRIMARY KEY (MENU_ITEM_ID),
  FOREIGN KEY (MENU_ITEM_TYPE_ID) REFERENCES MENU_ITEM_TYPES (MENU_ITEM_TYPE_ID));

CREATE TABLE ORDERS (
  ORDER_ID NUMBER(10, 0) NOT NULL AUTO_INCREMENT,
  ORDER_TIME TIMESTAMP(2) NOT NULL,
  PRIMARY KEY(ORDER_ID));

CREATE TABLE MENU_ITEM_ORDER (
  MENU_ITEM_ID NUMBER(10, 0) NOT NULL,
  ORDER_ID NUMBER(10, 0) NOT NULL,
  PRIMARY KEY (MENU_ITEM_ID),
  PRIMARY KEY (ORDER_ID));

INSERT INTO MENU_ITEM_TYPES (NAME) VALUES ('Sandwich');
INSERT INTO MENU_ITEM_TYPES (NAME) VALUES ('Side');
INSERT INTO MENU_ITEM_TYPES (NAME) VALUES ('Drink');

INSERT INTO MENU_ITEMS (NAME, MENU_ITEM_TYPE_ID, PRICE) VALUES ('Cheese Burger', 1, 10.50);
INSERT INTO MENU_ITEMS (NAME, MENU_ITEM_TYPE_ID, PRICE) VALUES ('Chicken Sandwich', 1, 10.00);
INSERT INTO MENU_ITEMS (NAME, MENU_ITEM_TYPE_ID, PRICE) VALUES ('Cheese Steak Supreme', 1, 15.00);
INSERT INTO MENU_ITEMS (NAME, MENU_ITEM_TYPE_ID, PRICE) VALUES ('Sweet Potato Fries', 2, 4.00);
INSERT INTO MENU_ITEMS (NAME, MENU_ITEM_TYPE_ID, PRICE) VALUES ('Fries', 2, 3.00);
INSERT INTO MENU_ITEMS (NAME, MENU_ITEM_TYPE_ID, PRICE) VALUES ('Coke a Cola', 3, 1.50);
INSERT INTO MENU_ITEMS (NAME, MENU_ITEM_TYPE_ID, PRICE) VALUES ('Sprite', 3, 1.50);
INSERT INTO MENU_ITEMS (NAME, MENU_ITEM_TYPE_ID, PRICE) VALUES ('Corona', 3, 2.50);
INSERT INTO MENU_ITEMS (NAME, MENU_ITEM_TYPE_ID, PRICE) VALUES ('Water', 3, 0);

DROP SEQUENCE hibernate_sequence;
CREATE SEQUENCE hibernate_sequence;