DROP TABLE MENU_ITEMS;
DROP TABLE ORDERS;

CREATE TABLE MENU_ITEMS (
  MENU_ITEM_ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR2(255) NOT NULL,
  PRICE NUMBER (4, 2) NOT NULL,
  PRIMARY KEY (MENU_ITEM_ID));

CREATE TABLE ORDERS (
  ORDER_ID NUMBER (10, 0) NOT NULL AUTO_INCREMENT,
  ORDER_TIME TIMESTAMP (2) NOT NULL,
  PRIMARY KEY(ORDER_ID));

CREATE TABLE MENU_ITEM_ORDER (
  MENU_ITEM_ID NUMBER(10, 0) NOT NULL,
  ORDER_ID NUMBER(10, 0) NOT NULL,
  PRIMARY KEY (MENU_ITEM_ID),
  PRIMARY KEY (ORDER_ID));



DROP SEQUENCE hibernate_sequence;
CREATE SEQUENCE hibernate_sequence;